# Generated by Django 6.0.4 on 2026-06-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='foto_usuario/'),
        ),
    ]
