# Generated by Django 6.0.4 on 2026-06-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tematica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
